/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Data;

import Business.Airline.Airline;
import Business.Airline.AirlineDirectory;
import Business.Airline.Flight;
import Business.Airline.FlightDirectory;

//import UserInterface.SupplierRole.OnlyviewforsearchJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author peichun
 */
public class FlightInformationJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    AirlineDirectory airlineDir;
    Airline air;

    /**
     * Creates new form ChooseFlightJPanel
     */
   

    public FlightInformationJPanel(JPanel upc, AirlineDirectory s) {
        initComponents();
        userProcessContainer = upc;
        airlineDir = s;
        
        refreshTable();
    }
    
    public void refreshTable() {
        int rowCount = masterScheduleTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)masterScheduleTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        for(Airline s : airlineDir.getAlList())
        for(Flight p : s.getFltList().getFltList()) {
            Object row[] = new Object[6];
            row[0] = s;
            row[1] = p.getFlightnumber();
            row[2] = p.getCty();
            row[3] = p.getTime();
            row[4] = p.getPrice();
            row[5] = p.getCapacity();
            air=s;
                                                                
            model.addRow(row);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        masterScheduleTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        SearchField = new javax.swing.JTextField();

        masterScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Airliner", "Flight number", "Destination", "Departure Time", "Price", "Capacity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        masterScheduleTable.setRowHeight(25);
        jScrollPane1.setViewportView(masterScheduleTable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Master Schedule");

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton)
                .addGap(182, 523, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed

        String info = SearchField.getText();
        Flight produc = null;
        Airline supll = null;
//        for(Airline s : airlineDir.getAlList())
//            if(s.getSupplyName().equals(info)){
////            if(p == null){
//                supll=s;
//                PreferFlightJPanel pfjp = new PreferFlightJPanel(userProcessContainer,s,produc);
//                userProcessContainer.add("PreferFlightJPanel", pfjp);
//                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//                layout.next(userProcessContainer);
//                return;
//                
//            } 
        for(Airline s : airlineDir.getAlList())
        for(Flight p : s.getFltList().getFltList()){
            p = s.getFltList().searchFlightString(info);
            supll=s;
            if(p != null){
                produc=p;
                CountryflightJPanel pfjp = new CountryflightJPanel(userProcessContainer,s,p);
                userProcessContainer.add("PreferFlightJPanel", pfjp);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                return;
            } 
//            if(s.getSupplyName().equals(info)){
//                PreferFlightJPanel pfjp = new PreferFlightJPanel(userProcessContainer,s);
//                userProcessContainer.add("PreferFlightJPanel", pfjp);
//                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//                layout.next(userProcessContainer);
//            }
//        
//            if(!s.getSupplyName().equals(info) & p!=null){
//                PreferFlightJPanel pfjp = new PreferFlightJPanel(userProcessContainer,s,p);
//                userProcessContainer.add("PreferFlightJPanel", pfjp);
//                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//                layout.next(userProcessContainer);
//             }
            //else{
               // JOptionPane.showMessageDialog(null, "This information does not exist!!","Information",JOptionPane.INFORMATION_MESSAGE);
                
            //}
          
//        userProcessContainer.add("PreferFlightJPanel", pfjp);
//        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
            
                
        }
        //if(produc==null & supll==null)
           // JOptionPane.showMessageDialog(null, "This information does not exist!!","Information",JOptionPane.INFORMATION_MESSAGE);
            if(produc == null)
                JOptionPane.showMessageDialog(null, "This information does not exist!!","Information",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_SearchButtonActionPerformed
   
    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable masterScheduleTable;
    // End of variables declaration//GEN-END:variables
}
