/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Airline.Flight;
import Business.Customer.Customer;
import Business.Department.Department;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.User.User;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class SelectEnterpriseJPanel extends javax.swing.JPanel {
    private JPanel upc;
    private Customer customer;
    private EcoSystem business;
    private Flight flight;
    /**
     * Creates new form SelectEnterpriseJPanel
     */
    public SelectEnterpriseJPanel(JPanel upc, Flight flight, Customer customer, EcoSystem business) {
        initComponents();
        this.upc = upc;
        this.customer = customer;
        this.business = business;
        this.flight = flight;
        countryLabel.setText(flight.getCty());
        populate();
    }
    
    public void populate(){
        List<Enterprise> exports = new ArrayList<>();
        for(Network network : business.getNetworkList()){
            for(Enterprise e: network.getEntList().getEnterpriseList()){
                if(e.getEntType() == Enterprise.EnterpriseType.Export){
                    exports.add(e);
                }
            }
        }
        List<Enterprise> selectedExports = new ArrayList<>();
        for(Enterprise enterprise : exports){
            for(Department department : enterprise.getDepartmentList().getDepList()){
                for(User user : department.getUserList().getUserList()){
                    if(user.getEmployee().getFlight() !=  null && user.getEmployee().getFlight().getCty().equals(flight.getCty())){
                        selectedExports.add(enterprise);
                    }
                }
            }
        }
        DefaultTableModel model = (DefaultTableModel)enterpriseTable.getModel();
        model.setRowCount(0);
        for(Enterprise e : selectedExports){
            Object row[] = new Object[2];
            row[0] = e.getNetworkName();
            row[1] = e;
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        enterpriseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network", "Enterprise"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseTable);
        if (enterpriseTable.getColumnModel().getColumnCount() > 0) {
            enterpriseTable.getColumnModel().getColumn(0).setResizable(false);
            enterpriseTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("Country");

        countryLabel.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        countryLabel.setText("jLabel2");

        jButton1.setText("Select Products >>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1)
                        .addGap(70, 70, 70)
                        .addComponent(countryLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jButton1)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(countryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTable enterpriseTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
